### Index method - Show all posts
GET http://localhost:3050/posts


### Show method - Show post by post_id
http://localhost:3050/posts/4

### Create method - Create new post
POST http://localhost:3050/create
Content-Type: application/json

{
    "title": "New post",
    "description": "New post created from post method",
    "rating": 3
}

### Create method - Create new post as Authorised/Logged in User
POST http://localhost:3050/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTg4NDAxNjYsInN1YiI6M30.pvfdzA0BXbfCjruIRRV1ZQ9CO_sKfr7q77Lgs123pQg

{
    "title": "New post",
    "description": "New post created from post method",
    "rating": 3
}

### Update method - Update existing post
PUT http://localhost:3050/posts/5
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTg4NDAxNjYsInN1YiI6M30.pvfdzA0BXbfCjruIRRV1ZQ9CO_sKfr7q77Lgs123pQg

{
    "title": "Updated post",
    "description": "Updated the post from put method",
    "rating": 4
}

### Delete method -  Delete post by ID
DELETE http://localhost:3050/posts/8


### Create a user
POST http://localhost:3050/sign_up/
Content-Type: application/json

{
    "username": "test3",
    "email": "test3@test.com",
    "password": "test3",
    "password_confirmation": "test3"
}


### Sign in with Correct details
POST http://localhost:3050/sign_in/
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "test3"
}