### Index method - Show all posts
GET http://localhost:3050/posts


### Show method - Show post by post_id
http://localhost:3050/posts/30

### Create method - Create new post
POST http://localhost:3050/create
Content-Type: application/json

{
    "title": "New post",
    "description": "New post created from post method",
    "rating": 3
}

### Create method - Create new post as Authorised/Logged in User
POST http://localhost:3050/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTg5OTAxNjcsInN1YiI6MX0.XbnxZ_UjnE5Unf2ZZE8dmaDV0FEIBJRlpjjCe2okxBw

{
    "title": "New post",
    "description": "New post created from post method",
    "rating": 3
}

### Update method - Update existing post
PUT http://localhost:3050/posts/8
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTk1ODM1OTMsInN1YiI6MX0.9J5Pfj8ol8hJLZyuRiDIWy3wP0pZwZYSb4MecYbIWTk

{
    "title": "Testing Edit function",
    "description": "Updated the post from put method",
    "rating": 4
}

### Delete method -  Delete post by ID
DELETE http://localhost:3050/posts/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTkyMzI5MzgsInN1YiI6MX0.rkzDbu0YOqL9Mku5ExPMHDctu7COZPYP3rN78kJ6Xqw


### Create a user
POST http://localhost:3050/sign_up/
Content-Type: application/json

{
    "username": "test3",
    "email": "test3@test.com",
    "password": "test3",
    "password_confirmation": "test3"
}


### Sign in with Correct details
POST http://localhost:3050/sign_in/
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

### Get current logged in user
GET http://localhost:3050/about


### Update Exisiting User:
PUT http://localhost:3050/user/7/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTkzMjM5MTEsInN1YiI6N30.sWqf8ZscwojVXeH5kDiCOOi33-GdF9YHpdUv5vzJJfM

{
    "about": "whats good papi"
}


### Get User Details
GET http://localhost:3050/user/7